apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: next-page
  template:
    metadata:
      labels:
        app: next-page
    spec:
      containers:
        - name: next-page
          image: next-page:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
