apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-page-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: next-page
  template:
    metadata:
      labels:
        app: next-page
    spec:
      containers:
        - name: next-page
          image: ghcr.io/ruu413/next-page:e1f7b15-1641317547 # {"$imagepolicy": "flux-system:next-page"}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
