apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-page-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: next-page
  template:
    metadata:
      labels:
        app: next-page
    spec:
      containers:
        - name: next-page
          image: next-page:6308800-1641246830 # {"$imagepolicy": "flux-system:next-page"}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
