---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: next-page
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: next-page
  filterTags:
    pattern: '[a-f0-9]+-(?P<ts>[0-9]+)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
# https://fluxcd.io/docs/guides/image-update/

