apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-page
  namespace: flux-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: next-page
  template:
    metadata:
      labels:
        app: next-page
    spec:
      containers:
        - name: next-page
          image: next-page:1 # {"$imagepolicy": "next-page"}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
