name: deploy docker image

on:
  push:
    branches: [ deployment ]
  pull_request:
    branches: [ deployment ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: set tag
        run: |-
          export TIMESTUMP=$(date +%s)
          export SHA=$(echo ${{ github.sha }} | cut -c1-7)
          echo "IMAGE_TAG=$SHA-$TIMESTUMP" >> $GITHUB_ENV
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: true
          tags: ghcr.io/ruu413/next-page:${{ env.IMAGE_TAG }}
